# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'YASwiftLib' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for YASwiftLib
    pod 'ReachabilitySwift'
    pod 'SideMenu'
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
    pod 'RealmSwift'
    pod 'CocoaLumberjack/Swift'
    pod 'IQKeyboardManagerSwift'
    pod 'IQDropDownTextField'
    pod 'StringExtensionHTML'
    pod 'NVActivityIndicatorView'
    pod 'UIDropDown'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
