# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YASwiftSample' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for YASwiftSample
    pod 'ReachabilitySwift'
    pod 'SideMenu' #, '~> 4.0.0'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Toast-Swift' #, '~> 5.0.1'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'RealmSwift'
    pod 'CocoaLumberjack/Swift'
    pod 'IQKeyboardManagerSwift'
    pod 'IQDropDownTextField'
    pod 'StringExtensionHTML'
    pod 'NVActivityIndicatorView'
    pod 'UIDropDown'
    # add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
    # add pods for any other desired Firebase products
    # https://firebase.google.com/docs/ios/setup#available-pods
    
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.0'
#        end
#    end
#end
